### ISSUE TITLE
automate collecting docs for each package

### ISSUE THREAD

**Issue by wheatjs** [vueuse/vscode-vueuse#3]
Would like to have a script we can perhaps run at build time to automatically collect and update the indexes in the extension for each VueUse package that we want to provide this kind of documentation for. For the main package it is pretty easy as we can just pull the `indexes.json` file. Since the main package seems to be the only one that provides that we might have to come up with something different for the other projects. If we can get the other ones to provide index files it would be a simple as collecting them and merging them. But I'd like to here what you guys think before doing anything @antfu @Tahul.

**Comment by wheatjs** [comment]
Another idea is if VSCode extensions support making http requests, we could have the extension fetch the latest indexes whenever the extension is loaded and update the current indexes so we don't have to publish a new version of the extension every time we add a new function

**Comment by antfu** [comment]
Both sounds good. We can provide a command like "Update VueUse function info" or something to allow users to do it manually.

**Comment by wheatjs** [comment]
Alright I'll implement that for the main vueuse package and until the other ones provide indexes I'll just have create another json file and merge them with the main ones

**Comment by wheatjs** [comment]
Functionality for this has been implemented for this in a28ee18. Once the other libraries have added indexes we can just update the json files in the extension, but for now they will rely on local versions.
